#!/data/data/com.termux/files/usr/bin/bash
set -euo pipefail
R="$(cd "$(dirname "$0")" && pwd)"
bash -n "$R/incident-orchestrator-worker.sh" "$R/adb-recovery-watchdog.sh" "$R/samantha-health-manager.sh" "$R/samantha-root-guardian.sh" "$R/incident-manager.sh" "$R/incident-close.sh" "$R/autonomous-engineering-close.sh" "$R/whatsapp-owner-send.sh"
! grep -q 'guardian.lock.*exec 9>&-' "$R/samantha-root-guardian.sh"
grep -q 'ensure_supervisor health_manager' "$R/samantha-root-guardian.sh"
grep -q 'ensure_supervisor incident_orchestrator' "$R/samantha-root-guardian.sh"
grep -q 'nohup env CLAW_RUNTIME_ROOT=.*9>&-' "$R/samantha-root-guardian.sh"
! grep -A2 'flock -n 9' "$R/adb-recovery-watchdog.sh" | grep -q '^exec 9>&-$'
! grep -q 'incident-notify.sh.*human_required' "$R/adb-recovery-watchdog.sh"
! grep -q 'incident-notify.sh.*human_required' "$R/samantha-health-manager.sh"
! grep -q 'incident-notify.sh.*human_required' "$R/boot-continuity-recovery.sh"
grep -q 'count.*-ge 2' "$R/incident-orchestrator-worker.sh"
grep -q 'human-boundary' "$R/incident-orchestrator-worker.sh"
grep -q 'grace_s=\$grace' "$R/samantha-health-manager.sh"
grep -q 'check_gateway' "$R/samantha-health-manager.sh"
grep -q 'grace_s=180' "$R/samantha-health-manager.sh"
grep -q 'kill_stale' "$R/samantha-health-manager.sh"
grep -q 'sleep.*9>&-' "$R/samantha-health-manager.sh"
grep -q 'check_supervisor root_guardian' "$R/samantha-health-manager.sh"
test "$(grep -c 'health-manager.heartbeat' "$R/samantha-health-manager.sh")" -ge 2
test -x "$R/health-verdict.py"
grep -q '127.0.0.1:5556 get-state' "$R/health-verdict.py"
grep -q 'notification.whatsapp' "$R/health-verdict.py"
grep -q 'notification.smtp' "$R/health-verdict.py"
test -x "$R/whatsapp-owner-send.sh"
grep -q 'gateway call send' "$R/whatsapp-owner-send.sh"
! grep -q 'openclaw message send' "$R/incident-manager.sh"
! grep -q 'openclaw message send' "$R/incident-close.sh"
! grep -q 'openclaw message send' "$R/autonomous-engineering-close.sh"
test -x "$R/adb-discover-endpoint.py"
python3 -m py_compile "$R/adb-discover-endpoint.py"
grep -q '_adb-tls-connect._tcp.local' "$R/adb-discover-endpoint.py"
test -x "$R/adb-recovery-readiness.py"
python3 -m py_compile "$R/adb-recovery-readiness.py"
grep -q 'adb-expected-serial' "$R/adb-recovery-watchdog.sh"
grep -q 'adb-discover-endpoint.py' "$R/adb-recovery-watchdog.sh"
grep -q 'adb-recovery-readiness.py' "$R/adb-recovery-watchdog.sh"
grep -q 'device.adb.recovery_readiness' "$R/health-verdict.py"
"$R/test-whatsapp-owner-send.sh"
echo 'incident runtime hardening: OK'

# Managed repair recovery must address the orchestrator API by component+scope, never incident id.
grep -q 'recover .*\$component.*\$scope.*--source orchestrator-worker' "$R/incident-orchestrator-worker.sh"
